# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://tinyqiang.github.io/TinyQiang/
date_format: "ordinal"
title: TinyQiang
subtitle: "越是憧憬，越是要风雨兼程！"
description: "TinyQiang's Blog"
keywords: TinyQiang, qiang
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: TinyQiang
organization: 爱存不存
organization_url: https://tinyqiang.github.io/TinyQiang/
github_username: TinyQiang
location: Shanghai, China
email: wzq.makeit@qq.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /about/
    label: About

  -
    href: /archives/
    label: Archives

  -
    href: /categories/
    label: Categories

  -
    href: /favorites/
    label: Favorites

  -
    href: /projects/
    label: Projects

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: TinyQiang/TinyQiang.github.io

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username:
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner:
    repo:
    oauth:
        client_id:
        client_secret:
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: TinyQiang
    repo: TinyQiang.github.io
    clientID: 9ba380c92e91d2a9b85c
    clientSecret: 9def192ccb6d66bd07e9cdbd5d2a5181a600030c
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # 是否支持全文搜索
    fulltext: false
    # 最多显示多少条搜索结果
    limit: 10

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-122302462-1
